version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebittwitter
      - app-gems:/app-gems

volumes:
  redis:
  postgres:
  app-gems:
