default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: my_twitter_development

test:
  <<: *default
  database: my_twitter_test

production:
  <<: *default
  database: my_twitter_production
  username: MyTwitter
  password: <%= ENV['MYTWITTER_DATABASE_PASSWORD'] %>